spring.application.name=backend



# ===========================
# PostgreSQL
# ===========================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookmanager}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}



spring.datasource.driver-class-name=org.postgresql.Driver





# ===========================
# JPA / Hibernate
# ===========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# Mostra SQL gerado pelo Hibernate
logging.level.org.hibernate.SQL=DEBUG


# Mostra valores enviados nos parâmetros ?
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# Mostra criação/alteração de tabelas
logging.level.org.hibernate.tool.schema=DEBUG


# Mostra eventos do EntityManager
logging.level.org.hibernate.orm=DEBUG


# Mostra operações de persistência
logging.level.org.springframework.orm.jpa=DEBUG





# ===========================
# Database Initialization
# ===========================

spring.sql.init.mode=always





# ===========================
# Servidor
# ===========================

server.port=8080





# ===========================
# JWT
# ===========================

jwt.secret=${JWT_SECRET}

jwt.expiration=${JWT_EXPIRATION:300000}





# ===========================
# Swagger
# ===========================

app.swagger.launch=${APP_SWAGGER_LAUNCH:true}