spring.application.name=backend


# ===========================
# PostgreSQL
# ===========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookmanager}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Di@s1988}

spring.datasource.driver-class-name=org.postgresql.Driver



# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# ===========================
# Database Initialization
# ===========================
spring.sql.init.mode=always



# ===========================
# Servidor
# ===========================
server.port=8080



# ===========================
# JWT
# ===========================
jwt.secret=${JWT_SECRET:MyVerySecretKeyForBookManagerApplication123456789}

jwt.expiration=${JWT_EXPIRATION:86400000}



# ===========================
# Swagger
# ===========================
app.swagger.launch=${APP_SWAGGER_LAUNCH:false}